spring.docker.compose.enabled=false
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
astra.jwt.secret=${ASTRA_JWT_SECRET}
astra.chat.encryption-key=${ASTRA_CHAT_ENCRYPTION_KEY}
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
